---
- name: Copy and Execute Script
  hosts: all
  become: yes

  tasks:
    - name: Copy script to remote host
      copy:
        src: /home/ubuntu/script.sh
        dest: /tmp/script.sh
        mode: 0755

    - name: Execute script
      shell: /tmp/script.sh
