---
- name: Deploy Apache2 Web Server with Local Files
  hosts: all
  become: true
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Install Apache2 web server
      apt:
        name: apache2
        state: present

    - name: Copy local index.html to the Apache document root
      copy:
        src: /home/ubuntu/assignment/index.html  # Replace with the actual path to index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Ensure Apache service is running and enabled
      service:
        name: apache2
        state: started
        enabled: true

    - name: Display the private IP address of the managed node
      debug:
        msg: "Access the web application at http://{{ ansible_default_ipv4.address }}/"

